Staging/home
HackIllinois/site-2020 pull request #24
Opened 2019-11-07 02:10 UTC by akong00

initial home page

2019-11-07 02:57 UTC, brianstrauch requested changes
Looks really good, let's make all the assets lower_camel_case and stick them in the assets folder, grouped by page, so assets/home/example_asset.svg
Not a fan of the svgs folder since pretty much everything is an SVG
Also assets starting with hackillinois_website are redundant

Looks really good, I want to play around with it before I approve it

2019-11-07 02:57 UTC, bstrauch24 commented on src/components/Home/index.jsx
> +  /* @media(max-width: 1000px){
Don't commit commented code! BIG NO NO

2019-11-07 02:57 UTC, bstrauch24 commented on src/components/Home/index.jsx
> +  /* @media(max-width: 1000px){
😡

2019-11-07 02:57 UTC, bstrauch24 commented on src/components/Home/index.jsx
> +const DescTitle = Styled.div`
What does desc mean? Description? If so write the whole word

2019-11-07 02:57 UTC, bstrauch24 commented on src/components/Home/index.jsx
> +  return({
Don't think the parentheses are necessary here

2019-11-07 02:57 UTC, bstrauch24 commented on src/components/Home/index.jsx
> +    const Descriptions = [
constants should be UPPER_SNAKE_CASE

2019-11-07 02:57 UTC, bstrauch24 commented on src/components/Home/index.jsx
> +    const Descriptions = [
I really like how you grouped all the text into objects here!! You might want to put all of these constants into a separate JS file though. They account for a lot of lines and detract from the CSS/JSX

2019-11-21 03:15 UTC, brianstrauch approved these changes

2019-11-21 03:21 UTC, Aitori approved these changes

2019-11-21 03:50 UTC, merged