Staging/schedule
HackIllinois/site-2020 pull request #71
Opened 2020-02-06 04:35 UTC by Aitori

Finished most of the schedule page save for the drop down with some ugly buttons but will update, need advice on designs

2020-02-06 16:22 UTC, brianstrauch requested changes
Looks great! Make sure you're filtering out events that happen before Friday or after Sunday. Also there's an event on Sunday that says 0:00pm haha

2020-02-06 16:22 UTC, bstrauch24 commented on src/components/NavBar/index.jsx
> +  { text: 'Schedule', to: '/schedule' },
Make sure you merge with dev. The only links that should be uncommented are /schedule, /maps, and /mentors

2020-02-06 16:24 UTC, bstrauch24 commented
One more thing, the scenery should overlap the billboard on mobile

<img width="349" alt="Screen Shot 2020-02-06 at 10 23 35 AM" src="https://user-images.githubusercontent.com/7474900/73956610-cdb4e700-48ca-11ea-9405-40d724736355.png">

2020-02-11 00:38 UTC, brianstrauch requested changes
Looks good but doesn't scroll for some reason

2020-02-11 03:53 UTC, Aitori commented
fixed the scroll issue, there was a div on top covering the entire thing but I shortened it, also removed the scroll bar if its not needed

2020-02-11 15:14 UTC, brianstrauch approved these changes

2020-02-11 15:14 UTC, merged